### ISSUE TITLE
Incorrect Link on Website

### ISSUE THREAD

**Issue by klonamy** [cluclead/panel-view#1]
Hello there,

first off great wrapper. So how did i get here and what is the problem.

I installed Whatsapp™ Messenger for Firefox.
So i followed the addon to github and after that there: http://add0n.com/whatsapp-messenger.html

On this site i tired to get to the chrome version of this addon and was linked to: https://chrome.google.com/webstore/detail/
That resulted in an error: 

> Ein Fehler ist aufgetreten.
> 
> Ihr Fehler wurde an Google gemeldet.
> Zurück zum Store

Of course next was the search in the Chrome Web Store and there i found it:
https://chrome.google.com/webstore/detail/whatsapp-messenger/infelompnbbancffeibkenmdbbmpoged?utm_source=chrome-ntp-icon
Please correct the link on your page. :)

Hope that helped.
KlonAmy

**Comment by cluclead** [comment]
Thanks for the report. It is fixed now
