### ISSUE TITLE
"A" checkbox in side-panel

### ISSUE THREAD

**Issue by temporarium** [cluclead/panel-view#10]
I couldn't find an explanation for what the "A" checkbox in the side-panel just above the settings gear is for. Could you please clarify. Thanks.

**Comment by cluclead** [comment]
On Firefox version (in contrast to Chrome), there is a permission request for allowing access to the audio device. In the Chrome version since the app is loaded in an isolated sandbox, there is no need for this extra feature. What is your browser?

**Comment by temporarium** [comment]
Ah, I'm on Firefox. Thanks for clearing it up.

But there is a setting for audio permissions in the extension settings for this addon, so why the need for another checkbox?

**Comment by cluclead** [comment]
These two are equal. If you change one, the other one should be changed as well. Since this option is something that users might change a lot that's the reason why it is implemented on the UI as well.
