### ISSUE TITLE
Changing language layout closes the addon window while typing

### ISSUE THREAD

**Issue by lovemytux** [cluclead/panel-view#4]
Hello there and great addon btw. :)
I am running your addon on Firefox (V 48), Linux OS (Arch) and Gnome 3.20 (Window Manager). 
When I am changing the language layout of my keyboard, the addon window closes and I have to reopen it in order to continue typing.. Luckily, you can continue from where you stopped and you don't lose your previous typed in text. 
Thanks

**Comment by cluclead** [comment]
What is the keyboard shortcut are you using? I guess the only workaround is to pin the panel while you are typing

**Comment by lovemytux** [comment]
SuperKey (Windows key) + Space. 
I will try your workaround. 
Thanks for the reply. :+1:

**Comment by cluclead** [comment]
Windows key is the problem here. Change it to a combination that does not require Windows key.

**Comment by lovemytux** [comment]
Okay then. But this could be changed right? I mean you should no be depended on the "change keyboard layout" combination. Or am I missing something here?
Thanks for your input btw :)

**Comment by cluclead** [comment]
Windows key is special. Hiding of the panel is not something we have control over. If an special key is pressed, Firefox closes all panel without the pinning attribute.

**Comment by lovemytux** [comment]
Hmmm, thanks for your inputs once again.
Keep up the good work :+1: 
Cheers
