### ISSUE TITLE
[Firefox] Why my panel icon is not green?

### ISSUE THREAD

**Issue by alexandre-mbm** [cluclead/panel-view#9]
It became so after the last update.

![whatsapp-messenger-firefox-black-icon](https://cloud.githubusercontent.com/assets/957501/19061597/702bf426-89c8-11e6-9678-4c0cdce71da6.png)

**Comment by cluclead** [comment]
I have decided to change the icon to match Firefox theme

**Comment by alexandre-mbm** [comment]
It would be interesting as "option".

**Comment by cluclead** [comment]
Okay, I'll add an option for that.
